version: "2"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: noms
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goconst
    - gocritic
    - gocyclo
    - dupl

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - test
  exclude-files:
    - ".*_test\\.go$"

run:
  timeout: 5m
  tests: true
